[2025-01-16T13:48:30.833+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_processing_dag.spark_submit_job manual__2025-01-16T13:48:29.508988+00:00 [queued]>
[2025-01-16T13:48:30.843+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_processing_dag.spark_submit_job manual__2025-01-16T13:48:29.508988+00:00 [queued]>
[2025-01-16T13:48:30.844+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-16T13:48:30.855+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): spark_submit_job> on 2025-01-16 13:48:29.508988+00:00
[2025-01-16T13:48:30.866+0000] {standard_task_runner.py:57} INFO - Started process 81 to run task
[2025-01-16T13:48:30.872+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'spark_processing_dag', 'spark_submit_job', 'manual__2025-01-16T13:48:29.508988+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/spark-processing.py', '--cfg-path', '/tmp/tmpo6ugyb1i']
[2025-01-16T13:48:30.874+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask spark_submit_job
[2025-01-16T13:48:30.923+0000] {task_command.py:416} INFO - Running <TaskInstance: spark_processing_dag.spark_submit_job manual__2025-01-16T13:48:29.508988+00:00 [running]> on host 9cbd1a8e8e69
[2025-01-16T13:48:31.047+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_processing_dag' AIRFLOW_CTX_TASK_ID='spark_submit_job' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T13:48:29.508988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T13:48:29.508988+00:00'
[2025-01-16T13:48:31.063+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-01-16T13:48:31.065+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose /opt/spark-apps/sample_spark_app.py /opt/spark-data/input /opt/spark-data/output
[2025-01-16T13:48:31.477+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-01-16T13:48:31.479+0000] {spark_submit.py:491} INFO - /home/***/.local/lib/python3.8/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript
[2025-01-16T13:48:31.534+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose /opt/spark-apps/sample_spark_app.py /opt/spark-data/input /opt/spark-data/output. Error code is: 1.
[2025-01-16T13:48:31.555+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_processing_dag, task_id=spark_submit_job, execution_date=20250116T134829, start_date=20250116T134830, end_date=20250116T134831
[2025-01-16T13:48:31.611+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task spark_submit_job (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark --verbose /opt/spark-apps/sample_spark_app.py /opt/spark-data/input /opt/spark-data/output. Error code is: 1.; 81)
[2025-01-16T13:48:31.702+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-16T13:48:31.745+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
